// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqfbuyqiylcgxrgpcuqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxZmJ1eXFpeWxjZ3hyZ3BjdXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDY3NDMsImV4cCI6MjA2MDQ4Mjc0M30.o-Wkh18mqTdv3PpN4GHpimHnx01w7iLv5RVDt23lU80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);